UPDATE TB_FREQUENCIA_ALUNOS SET DT_ENTRADA = '2018/09/13' WHERE CD_REGISTRO = 1;

UPDATE TB_ALUNOS SET CD_MODALIDADE = 1 WHERE CD_REGISTRO = 1;

DELETE FROM TB_MODALIDADES WHERE CD_MODALIDADE = 1;

UPDATE TB_ALUNOS SET SITUACAO = TRUE WHERE CD_REGISTRO = 3;

UPDATE TB_ALUNOS SET NOME = 'A',CPF = 'BDSFSSF' WHERE CD_REGISTRO = 4;

UPDATE TB_DESPESAS_PROGRAMADAS SET PAGO = false WHERE NM_DESPESA = 'Luz';

UPDATE TB_HISTORICO_PAGAMENTOS_ALUNOS SET VALOR_PAGO = NULL,DT_PAGAMENTO = NULL WHERE CD_REGISTRO = 3 AND DT_PAGAMENTO IS NULL;

UPDATE TB_HISTORICO_PAGAMENTOS_ALUNOS SET PROXIMO_VENCIMENTO = '2018/09/20' WHERE CD_REGISTRO = 3 AND DT_PAGAMENTO IS NULL;